#' Theme System for zztab2fig
#'
#' @description Functions for creating, managing, and applying themes to LaTeX
#'   tables generated by t2f(). Includes built-in themes for common journal
#'   styles (APA, Nature, NEJM) and support for custom themes.
#'
#' @name themes
NULL

# Theme environment for global state
.t2f_env <- new.env(parent = emptyenv())
.t2f_env$current_theme <- NULL
.t2f_env$custom_themes <- list()

#' Create a t2f theme
#'
#' @description Construct a theme object that controls the appearance of tables
#'   generated by t2f().
#'
#' @param name Character string. Display name for the theme.
#' @param scolor LaTeX color specification for alternating row shading (e.g.,
#'   "blue!10"). Set to "white" or use striped=FALSE to disable.
#' @param header_bold Logical. If TRUE, table headers are rendered in bold.
#' @param header_color LaTeX color for header background. NULL for no
#'   background.
#' @param font_size LaTeX font size command (e.g., "footnotesize", "small").
#'   NULL for default size.
#' @param document_class LaTeX document class. Defaults to "article".
#' @param extra_packages List of additional LaTeX package specifications.
#' @param booktabs Logical. If TRUE, uses booktabs package for professional
#'   horizontal rules.
#' @param striped Logical. If TRUE, applies alternating row colors.
#'
#' @return A t2f_theme object (list with class "t2f_theme").
#'
#' @examples
#' \dontrun{
#' my_theme <- t2f_theme(
#'   name = "custom",
#'   scolor = "green!8",
#'   header_bold = TRUE,
#'   font_size = "small"
#' )
#' t2f_theme_set(my_theme)
#' t2f(mtcars)
#' }
#'
#' @export
t2f_theme <- function(name = "custom",
                      scolor = "blue!10",
                      header_bold = TRUE,
                      header_color = NULL,
                      font_size = NULL,
                      document_class = "article",
                      extra_packages = NULL,
                      booktabs = TRUE,
                      striped = TRUE) {
  structure(
    list(
      name = name,
      scolor = scolor,
      header_bold = header_bold,
      header_color = header_color,
      font_size = font_size,
      document_class = document_class,
      extra_packages = extra_packages,
      booktabs = booktabs,
      striped = striped
    ),
    class = "t2f_theme"
  )
}

#' Set the global t2f theme
#'
#' @description Set the default theme for all subsequent t2f() calls. The theme
#'   can be overridden by passing a theme argument directly to t2f().
#'
#' @param theme A t2f_theme object or character string naming a built-in theme
#'   ("minimal", "apa", "nature", "nejm").
#'
#' @return Invisibly returns the previous theme.
#'
#' @examples
#' \dontrun{
#' old_theme <- t2f_theme_set("nejm")
#' t2f(mtcars)
#' t2f_theme_set(old_theme)
#' }
#'
#' @export
t2f_theme_set <- function(theme) {
  if (is.character(theme)) {
    theme <- get_builtin_theme(theme)
  }
  if (!inherits(theme, "t2f_theme") && !is.null(theme)) {
    stop("`theme` must be a t2f_theme object or theme name", call. = FALSE)
  }
  old <- .t2f_env$current_theme
  .t2f_env$current_theme <- theme
  invisible(old)
}

#' Get the current global t2f theme
#'
#' @description Retrieve the currently active global theme.
#'
#' @return The current t2f_theme object, or NULL if no theme is set.
#'
#' @export
t2f_theme_get <- function() {
  .t2f_env$current_theme
}

#' Register a custom theme
#'
#' @description Register a custom theme so it can be referenced by name in
#'   t2f() calls and t2f_theme_set(). This allows you to define journal-specific
#'   themes once and reuse them throughout your project.
#'
#' @param theme A t2f_theme object created with t2f_theme().
#' @param name Optional name to register the theme under. If NULL, uses the
#'   theme's internal name.
#' @param overwrite Logical. If TRUE, overwrites any existing theme with the
#'   same name. Default FALSE.
#'
#' @return Invisibly returns the theme object.
#'
#' @examples
#' \dontrun{
#' # Create and register a custom JAMA theme
#' jama <- t2f_theme(
#'   name = "jama",
#'   scolor = "white",
#'   header_bold = TRUE,
#'   font_size = "small",
#'   booktabs = TRUE,
#'   striped = FALSE
#' )
#' t2f_theme_register(jama)
#'
#' # Now use it by name
#' t2f(mtcars, theme = "jama")
#'
#' # Or set it globally
#' t2f_theme_set("jama")
#' }
#'
#' @export
t2f_theme_register <- function(theme, name = NULL, overwrite = FALSE) {
  if (!inherits(theme, "t2f_theme")) {
    stop("`theme` must be a t2f_theme object", call. = FALSE)
  }

  reg_name <- name %||% theme$name
  reg_name <- tolower(reg_name)

  # Check for built-in theme name collision

  builtin_names <- c("minimal", "apa", "nature", "nejm")
  if (reg_name %in% builtin_names) {
    stop("Cannot register theme with built-in name '", reg_name,
         "'. Choose a different name.", call. = FALSE)
  }

  # Check for existing custom theme

  if (reg_name %in% names(.t2f_env$custom_themes) && !overwrite) {
    stop("Theme '", reg_name, "' is already registered. ",
         "Use overwrite = TRUE to replace it.", call. = FALSE)
  }

  .t2f_env$custom_themes[[reg_name]] <- theme
  message("Theme '", reg_name, "' registered successfully.")
  invisible(theme)
}

#' Unregister a custom theme
#'
#' @description Remove a previously registered custom theme.
#'
#' @param name Character string. Name of the theme to unregister.
#'
#' @return Invisibly returns TRUE if the theme was removed, FALSE if it was not
#'   found.
#'
#' @examples
#' \dontrun{
#' t2f_theme_unregister("jama")
#' }
#'
#' @export
t2f_theme_unregister <- function(name) {
  name <- tolower(name)

  if (name %in% names(.t2f_env$custom_themes)) {
    .t2f_env$custom_themes[[name]] <- NULL
    message("Theme '", name, "' unregistered.")
    invisible(TRUE)
  } else {
    message("Theme '", name, "' not found in registry.")
    invisible(FALSE)
  }
}

#' Clear all custom themes
#'
#' @description Remove all registered custom themes, restoring only built-in
#'   themes.
#'
#' @return Invisibly returns the number of themes removed.
#'
#' @export
t2f_theme_clear <- function() {
  n <- length(.t2f_env$custom_themes)
  .t2f_env$custom_themes <- list()
  if (n > 0) {
    message("Cleared ", n, " custom theme(s).")
  }
  invisible(n)
}

#' Resolve theme from argument or global setting
#'
#' @param theme Theme argument from t2f() call (can be NULL, character, or
#'   t2f_theme object).
#' @return A t2f_theme object or NULL.
#' @keywords internal
resolve_theme <- function(theme) {
  if (is.null(theme)) {
    return(t2f_theme_get())
  }
  if (is.character(theme)) {
    return(get_builtin_theme(theme))
  }
  if (inherits(theme, "t2f_theme")) {
    return(theme)
  }
  stop("`theme` must be NULL, a theme name, or a t2f_theme object",
    call. = FALSE
  )
}

#' Get a theme by name
#'
#' @description Look up a theme by name, checking both built-in themes and
#'   registered custom themes.
#'
#' @param name Character string. Name of the theme.
#' @return A t2f_theme object.
#' @keywords internal
get_builtin_theme <- function(name) {
  name <- tolower(name)

 # Check built-in themes first
  builtin <- switch(name,
    "minimal" = t2f_theme_minimal(),
    "apa" = t2f_theme_apa(),
    "nature" = t2f_theme_nature(),
    "nejm" = t2f_theme_nejm(),
    NULL
  )

  if (!is.null(builtin)) {
    return(builtin)
  }

 # Check custom theme registry
  if (name %in% names(.t2f_env$custom_themes)) {
    return(.t2f_env$custom_themes[[name]])
  }

 # Theme not found
  available <- t2f_list_themes()
  stop("Unknown theme: '", name, "'. Available themes: ",
       paste(available, collapse = ", "),
       call. = FALSE)
}

#' List available themes
#'
#' @description List all available themes, including both built-in themes and
#'   registered custom themes.
#'
#' @param builtin_only Logical. If TRUE, only list built-in themes. Default
#'   FALSE.
#'
#' @return Character vector of available theme names.
#'
#' @examples
#' t2f_list_themes()
#' t2f_list_themes(builtin_only = TRUE)
#'
#' @export
t2f_list_themes <- function(builtin_only = FALSE) {
  builtin <- c("minimal", "apa", "nature", "nejm")
  if (builtin_only) {
    return(builtin)
  }
  custom <- names(.t2f_env$custom_themes)
  c(builtin, custom)
}

# Built-in Themes

#' Minimal theme
#'
#' @description A clean, minimal theme with light gray shading and no extra
#'   formatting. Suitable for general-purpose use.
#'
#' @return A t2f_theme object.
#'
#' @export
t2f_theme_minimal <- function() {
  t2f_theme(
    name = "minimal",
    scolor = "gray!5",
    header_bold = TRUE,
    header_color = NULL,
    font_size = NULL,
    document_class = "article",
    extra_packages = list(
      geometry(margin = "15mm")
    ),
    booktabs = TRUE,
    striped = TRUE
  )
}

#' APA theme
#'
#' @description Theme following American Psychological Association (APA 7th
#'   edition) table guidelines. Characterized by no row shading, bold headers,
#'   and booktabs-style horizontal rules.
#'
#' @return A t2f_theme object.
#'
#' @export
t2f_theme_apa <- function() {
  t2f_theme(
    name = "apa",
    scolor = "white",
    header_bold = TRUE,
    header_color = NULL,
    font_size = NULL,
    document_class = "article",
    extra_packages = list(
      geometry(margin = "1in", paper = "letterpaper"),
      "\\usepackage{times}"
    ),
    booktabs = TRUE,
    striped = FALSE
  )
}

#' Nature theme
#'
#' @description Theme following Nature journal table styling. Uses Helvetica
#'   font, light gray row shading, and compact spacing.
#'
#' @return A t2f_theme object.
#'
#' @export
t2f_theme_nature <- function() {
  t2f_theme(
    name = "nature",
    scolor = "gray!8",
    header_bold = TRUE,
    header_color = NULL,
    font_size = "small",
    document_class = "article",
    extra_packages = list(
      geometry(margin = "15mm"),
      "\\usepackage{helvet}",
      "\\renewcommand{\\familydefault}{\\sfdefault}"
    ),
    booktabs = TRUE,
    striped = TRUE
  )
}

#' NEJM theme
#'
#' @description Theme following New England Journal of Medicine table styling.
#'   Characterized by light yellow alternating row striping, sans-serif font
#'   (Helvetica), booktabs horizontal rules, and compact spacing.
#'
#' @details NEJM tables are designed for maximum clarity and professional
#'   appearance in medical publications. Key characteristics:
#'
#' - Light yellow alternating row colors
#' - Sans-serif font (Helvetica/Arial family)
#' - Booktabs-style horizontal rules (\\toprule, \\midrule, \\bottomrule)
#' - Compact column spacing (4pt)
#' - Slightly increased row spacing (1.15 stretch) for readability
#' - Footnotesize font for space efficiency
#'
#' @return A t2f_theme object.
#'
#' @examples
#' \dontrun{
#' t2f_theme_set(t2f_theme_nejm())
#' t2f(mtcars[1:10, 1:5], filename = "nejm_table")
#' }
#'
#' @export
t2f_theme_nejm <- function() {
  t2f_theme(
    name = "nejm",
    scolor = "yellow!8",
    header_bold = TRUE,
    header_color = "yellow!15",
    font_size = "footnotesize",
    document_class = "article",
    extra_packages = list(
      geometry(margin = "20mm", paper = "letterpaper"),
      "\\usepackage{helvet}",
      "\\renewcommand{\\familydefault}{\\sfdefault}",
      "\\usepackage{microtype}",
      "\\setlength{\\tabcolsep}{4pt}",
      "\\renewcommand{\\arraystretch}{1.15}"
    ),
    booktabs = TRUE,
    striped = TRUE
  )
}

#' Print method for t2f_theme objects
#'
#' @param x A t2f_theme object.
#' @param ... Additional arguments (ignored).
#' @return Invisibly returns x.
#' @export
print.t2f_theme <- function(x, ...) {
  cat("t2f theme:", x$name, "\n")
  cat("  Row shading:", if (x$striped) x$scolor else "none", "\n")
  cat("  Header bold:", x$header_bold, "\n")
  cat("  Font size:", if (is.null(x$font_size)) "default" else x$font_size, "\n")
  cat("  Document class:", x$document_class, "\n")
  cat("  Booktabs:", x$booktabs, "\n")
  if (!is.null(x$extra_packages) && length(x$extra_packages) > 0) {
    cat("  Extra packages:", length(x$extra_packages), "specified\n")
  }
  invisible(x)
}

#' Apply theme settings to t2f parameters
#'
#' @description Merge theme settings with explicitly provided t2f() arguments.
#'   Explicit arguments take precedence over theme settings.
#'
#' @param theme A t2f_theme object.
#' @param scolor User-provided scolor (NULL to use theme default).
#' @param document_class User-provided document_class (NULL to use theme
#'   default).
#' @param extra_packages User-provided extra_packages (combined with theme
#'   packages).
#'
#' @return A list with resolved parameter values.
#' @keywords internal
apply_theme_settings <- function(theme, scolor = NULL, document_class = NULL,
                                 extra_packages = NULL) {
  if (is.null(theme)) {
    return(list(
      scolor = scolor %||% "blue!10",
      document_class = document_class %||% "article",
      extra_packages = extra_packages,
      header_bold = TRUE,
      font_size = NULL,
      booktabs = TRUE,
      striped = TRUE
    ))
  }

  # Theme provides defaults; explicit args override
  resolved_scolor <- scolor %||% theme$scolor
  resolved_class <- document_class %||% theme$document_class

  # Combine extra_packages: theme packages first, then user packages
  combined_packages <- c(theme$extra_packages, extra_packages)
  if (length(combined_packages) == 0) combined_packages <- NULL

  # Add font size command if specified in theme
  font_packages <- NULL
  if (!is.null(theme$font_size)) {
    font_packages <- paste0("\\", theme$font_size)
  }

  list(
    scolor = resolved_scolor,
    document_class = resolved_class,
    extra_packages = combined_packages,
    header_bold = theme$header_bold,
    font_size = theme$font_size,
    booktabs = theme$booktabs,
    striped = theme$striped,
    font_packages = font_packages
  )
}

#' Null-coalescing operator
#' @keywords internal
`%||%` <- function(x, y) if (is.null(x)) y else x
