#' Typst Post-Processing Pipeline
#'
#' @description Post-processes the .typ file generated by tinytable before
#'   Typst compilation. Adds features that tinytable does not natively
#'   support: page sizing, font family, caption placement, separator
#'   lines, and compact footnotes.
#'
#' @name zzt2f-postprocess
#' @keywords internal
NULL

#' Post-process Typst source lines
#'
#' @param lines Character vector of .typ file lines.
#' @param opts Named list of options:
#'   \describe{
#'     \item{font_family}{Character or NULL. Typst font name.}
#'     \item{caption_above}{Logical. Place caption above table.}
#'     \item{separator_row}{Integer or NULL. 1-based data row index
#'       where a horizontal line should be inserted (e.g., to separate
#'       coefficients from summary statistics).}
#'     \item{n_cols}{Integer or NULL. Number of table columns (needed
#'       for separator hline).}
#'     \item{compact_footnotes}{Logical. Style footnotes smaller.}
#'   }
#' @return Modified character vector.
#' @keywords internal
postprocess_typst <- function(lines, opts = list()) {
  lines <- pp_page_size(lines)
  lines <- pp_font_family(lines, opts$font_family)
  if (isTRUE(opts$caption_above)) {
    lines <- pp_caption_above(lines)
  }
  if (!is.null(opts$separator_row) && !is.null(opts$n_cols)) {
    lines <- pp_separator_hline(lines, opts$separator_row,
                                opts$n_cols)
  }
  if (isTRUE(opts$compact_footnotes)) {
    lines <- pp_compact_footnotes(lines)
  }
  lines
}

#' Prepend page size directive
#' @param lines Character vector.
#' @return Modified character vector.
#' @keywords internal
pp_page_size <- function(lines) {
  directive <- paste0(
    "#set page(width: auto, height: auto, ",
    "margin: (x: 5pt, y: 5pt))"
  )
  c(directive, lines)
}

#' Insert font family directive
#' @param lines Character vector.
#' @param font_family Character or NULL.
#' @return Modified character vector.
#' @keywords internal
pp_font_family <- function(lines, font_family) {
  if (is.null(font_family)) return(lines)
  directive <- paste0('#set text(font: "', font_family, '")')
  idx <- grep("#show figure: set block", lines, fixed = TRUE)
  if (length(idx) == 0) {
    return(c(lines[1], directive, lines[-1]))
  }
  i <- idx[1]
  c(lines[seq_len(i - 1)], directive, lines[i:length(lines)])
}

#' Move caption above table
#' @param lines Character vector.
#' @return Modified character vector.
#' @keywords internal
pp_caption_above <- function(lines) {
  has_caption <- any(grepl("caption:", lines, fixed = TRUE))
  if (!has_caption) return(lines)

  idx <- grep("#show figure: set block", lines, fixed = TRUE)
  if (length(idx) == 0) return(lines)
  i <- idx[1]

  rule <- "#set figure.caption(position: top)"
  c(lines[seq_len(i - 1)], rule, lines[i:length(lines)])
}

#' Insert separator horizontal line in table
#' @param lines Character vector.
#' @param separator_row Integer. 1-based data row where separator goes.
#'   The hline appears above this row (between row separator_row-1 and
#'   separator_row). The y coordinate in Typst is separator_row + 1
#'   (accounting for the header row).
#' @param n_cols Integer. Number of table columns.
#' @return Modified character vector.
#' @keywords internal
pp_separator_hline <- function(lines, separator_row, n_cols) {
  y_pos <- as.integer(separator_row) + 1L
  hlines <- vapply(y_pos, function(y) {
    paste0(
      " table.hline(y: ", y,
      ", start: 0, end: ", n_cols,
      ", stroke: 0.05em + black),"
    )
  }, character(1L))
  idx <- grep("// tinytable lines before", lines, fixed = TRUE)
  if (length(idx) == 0) return(lines)
  i <- idx[1]
  c(lines[seq_len(i)], hlines, lines[(i + 1):length(lines)])
}

#' Style footnotes to be compact
#' @param lines Character vector.
#' @return Modified character vector.
#' @keywords internal
pp_compact_footnotes <- function(lines) {
  idx <- grep("// tinytable notes after", lines, fixed = TRUE)
  if (length(idx) == 0) return(lines)

  for (i in idx) {
    for (j in (i + 1):min(i + 20, length(lines))) {
      if (grepl("table\\.cell.*text\\(\\[", lines[j])) {
        lines[j] <- sub(
          "table\\.cell\\(",
          "table.cell(inset: (y: 1pt), ",
          lines[j]
        )
        lines[j] <- sub(
          "text\\(",
          "text(size: 0.75em, ",
          lines[j]
        )
      }
      if (grepl("^\\s*\\)", lines[j])) break
    }
  }
  lines
}
